<script setup lang="ts">
import { VueQueryDevtools } from '@tanstack/vue-query-devtools';
import { computed, ref, toValue } from 'vue';
import { useGetChannelById } from '@/api/generated/channels/channels';

// Generated by orval from apps/api/openapi.json - see README.md.
// Requests go to /api/*; Vite proxies them to the api app on :3001.
const channelId = ref('clx1abc123def');

// The query key includes the ref, so editing the id refetches.
const { data, isPending, isError } = useGetChannelById(channelId);

const channel = computed(() => (data.value?.status === 200 ? data.value.data : null));
const notFound = computed(() => data.value?.status === 404);
console.log(toValue(channel), 'channel')
</script>

<template>
  <div class="min-h-screen bg-gray-900 p-8 text-white">
    <h1 class="mb-6 text-2xl font-bold">Fox Sphere Admin</h1>

    <label class="mb-6 block max-w-md">
      <span class="mb-1 block text-sm text-gray-400">Channel id</span>
      <input
        v-model="channelId"
        class="w-full rounded border border-gray-700 bg-gray-800 px-3 py-2"
      />
    </label>

    <p v-if="isPending">Loading...</p>
    <p
      v-else-if="isError"
      class="text-red-400"
    >
      Request failed
    </p>
    <p
      v-else-if="notFound"
      class="text-amber-400"
    >
      Channel not found
    </p>
    <dl
      v-else-if="channel"
      class="grid max-w-md grid-cols-2 gap-y-1"
    >
      <dt class="text-gray-400">Login</dt>
      <dd>{{ channel.login }}</dd>
      <dt class="text-gray-400">Display name</dt>
      <dd>{{ channel.displayName }}</dd>
      <dt class="text-gray-400">Twitch id</dt>
      <dd>{{ channel.twitchId }}</dd>
      <dt class="text-gray-400">Status</dt>
      <dd>{{ channel.status }}</dd>
      <dt class="text-gray-400">Bot is mod</dt>
      <dd>{{ channel.botIsMod }}</dd>
    </dl>

    <!-- Query cache inspector. Ships as a no-op in a production build. -->
    <VueQueryDevtools />
  </div>
</template>
