import { globalIgnores } from 'eslint/config';
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript';
import pluginVue from 'eslint-plugin-vue';
import pluginVitest from '@vitest/eslint-plugin';
import pluginOxlint from 'eslint-plugin-oxlint';
import skipFormatting from 'eslint-config-prettier/flat';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

// To allow more languages other than `ts` in `.vue` files, uncomment the following lines:
// import { configureVueProject } from '@vue/eslint-config-typescript'
// configureVueProject({ scriptLangs: ['ts', 'tsx'] })
// More info at https://github.com/vuejs/eslint-config-typescript/#advanced-setup

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default defineConfigWithVueTs(
  {
    name: 'app/files-to-lint',
    files: ['**/*.{vue,ts,mts,tsx}'],
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: __dirname,
        projectService: true,
      },
    },
  },

  globalIgnores(['**/dist/**', '**/dist-ssr/**', '**/coverage/**', 'orval.config.ts']),

  ...pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,

  {
    name: 'app/compiler-macros',
    rules: {
      // `defineProps`/`defineEmits`/`defineModel` are compiler macros, available as
      // globals inside `<script setup>` - importing them collides with the generated
      // declaration and fails `vue-tsc` with TS2440. The rule is fixable, so with
      // `source.fixAll.eslint` on save it also strips an import an editor tool re-added.
      'vue/no-import-compiler-macros': 'error',
    },
  },

  // Vendored shadcn-vue primitives (regenerated by the shadcn CLI, never edited
  // by hand): their single-word names and optional props are upstream conventions,
  // so the house Vue rules do not apply here.
  {
    name: 'app/vendored-ui-overrides',
    files: ['src/components/ui/**/*.vue'],
    rules: {
      'vue/multi-word-component-names': 'off',
      'vue/require-default-prop': 'off',
    },
  },

  {
    ...pluginVitest.configs.recommended,
    files: ['src/**/*.test.ts'],
  },

  ...pluginOxlint.buildFromOxlintConfigFile('.oxlintrc.json'),

  skipFormatting,
);
